repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  # Python-specific hooks
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.8
    hooks:
      - id: docformatter
        args: [-i, -d, --config, pyproject.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/netromdk/vermin
    rev: v1.8.0
    hooks:
      - id: vermin
        args:
          [
            "--lint",
            "--no-make-paths-absolute",
            "--eval-annotations",
            "--backport",
            "argparse",
            "--backport",
            "typing",
            "--backport",
            "asyncio",
            "--backport",
            "dataclasses",
            "--backport",
            "enum",
            "-t=3.10-",
            "--violations",
            "--no-tips",
          ]
